# Railway deployment configuration
[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[healthcheck]
  path = "/_stcore/health"
