# Streamlit Community Cloud Secrets Template
# Copy this content to your Streamlit app's secrets in the dashboard

# API Keys (optional - app works without them but with limited data)
KALSHI_API_KEY = "your_kalshi_api_key_here"
KALSHI_API_SECRET = "your_kalshi_api_secret_here"
POLYMARKET_API_KEY = "your_polymarket_api_key_here"

# Other configuration
ENVIRONMENT = "production"
